### ISSUE TITLE
[p0] CI broken on main: AppDelegateTests.swift fails to compile (actor isolation)

### ISSUE THREAD

**Issue by yashasg** [yashasg/fantastic-octo-fortnight#705]
CI on `main` (HEAD `9bf1a3b`) fails on the `Build & Test` job. The latest 3 main runs all failed/cancelled.

## Error
```
Tests/EyePostureReminderTests/Services/AppDelegateTests.swift:102:38: error:
  call to main actor-isolated instance method 'settings(for:)' in a synchronous nonisolated context
  snapshot: { settings.settings(for: .eyes) },
```

The `SettingsClient.snapshot` closure is `@Sendable () -> ReminderSettings`. It captures a `@MainActor SettingsStore` and calls a `@MainActor` instance method synchronously, which the CI Swift compiler rejects under strict concurrency. Local Xcode 26.4 is more permissive and lets it through, masking the regression introduced by PR #699 and friends.

## Blast radius
- Every PR rebased on main fails `Build & Test` on this exact compile error (e.g. PR #703, PR #704).
- `./scripts/build.sh all` is wedged in CI.

## Fix
In `AppDelegateTests.makeAppFeatureStore`, capture the snapshot value once on the main actor (the test class is already `@MainActor`) and return that captured value from the closure.

## Evidence
- Failing job: https://github.com/yashasg/fantastic-octo-fortnight/actions/runs/25882666516
- Workflow run on main #700: failure
- Workflow run on main #699: cancelled
- Workflow run on main #696: cancelled
